apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chat-system
  labels:
    app: frontend
    app.kubernetes.io/part-of: chat-system
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30173
      protocol: TCP
      name: http
